// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Windows.Forms.Analyzers.Diagnostics;
using System.Windows.Forms.CSharp.Generators.ApplicationConfiguration;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Testing;

namespace System.Windows.Forms.Analyzers.Tests;

public partial class ApplicationConfigurationGeneratorTests
{
    [Theory]
    [InlineData(null, "SystemAware")]
    [InlineData("", "SystemAware")]
    [InlineData("SystemAware", "SystemAware")]
    [InlineData("DpiUnaware", "DpiUnaware")]
    [InlineData("PerMonitor", "PerMonitor")]
    [InlineData("PerMonitorV2", "PerMonitorV2")]
    [InlineData("DpiUnawareGdiScaled", "DpiUnawareGdiScaled")]
    [InlineData("permonitorv2", "PerMonitorV2")]
    [InlineData("1", "SystemAware")]
    public async Task CS_ApplicationConfigurationGenerator_sdk_dpi_reuses_canonical_parser(string? value, string expected)
    {
        var test = CreateSdkDpiTest(value);
        ExpectSdkHighDpiMode(test, expected);
        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Theory]
    [InlineData("NotAnUpstreamSetting")]
    [InlineData("999")]
    [InlineData("SystemAware\"<&>")]
    public async Task CS_ApplicationConfigurationGenerator_sdk_dpi_invalid_value_reports_original_diagnostic(string value)
    {
        var test = CreateSdkDpiTest(value);
        test.TestState.ExpectedDiagnostics.Add(DiagnosticResult.CompilerError(DiagnosticIDs.PropertyCantBeSetToValue));
        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Theory]
    [InlineData("")]
    [InlineData("false")]
    public async Task CS_ApplicationConfigurationGenerator_caller_owned_dpi_is_not_parsed(string generates)
    {
        var test = CreateSdkDpiTest("NotAnUpstreamSetting", generates);
        await test.RunAsync(TestContext.Current.CancellationToken);
    }

    private static Verifiers.CSharpIncrementalSourceGeneratorVerifier<ApplicationConfigurationGenerator>.Test CreateSdkDpiTest(
        string? value, string generates = "true")
    {
        string property = value is null ? string.Empty : $"build_property.ApplicationHighDpiMode = {value}";
        return new()
        {
            TestState =
            {
                OutputKind = OutputKind.WindowsApplication,
                Sources =
                {
                    "ApplicationConfiguration.Initialize();",
                    generates == "true" ? SdkConfiguration
                        : "internal static class ApplicationConfiguration { internal static void Initialize() { } }",
                },
                AnalyzerConfigFiles =
                {
                    ("/.globalconfig", $"""
                    is_global = true

                    build_property.LibreWinFormsSdkOwnsApplicationConfiguration = true
                    build_property.LibreWinFormsSdkGeneratesApplicationConfiguration = {generates}
                    {property}
                    """),
                },
            },
        };
    }

    private static void ExpectSdkHighDpiMode(
        Verifiers.CSharpIncrementalSourceGeneratorVerifier<ApplicationConfigurationGenerator>.Test test, string mode)
    {
        // Independent source oracle. The existing verifier uses .NET Framework
        // 4.7.2, which lacks these modern APIs; actual installed consumers below
        // separately require the real method/enum to compile without diagnostics.
        test.TestState.GeneratedSources.Add((typeof(ApplicationConfigurationGenerator),
            "LibreWinForms.ApplicationHighDpiMode.g.cs", $$"""
            // <auto-generated />
            internal static partial class ApplicationConfiguration
            {
                static partial void ConfigureHighDpiMode()
                {
                    global::System.Windows.Forms.Application.{|CS0117:SetHighDpiMode|}({|CS0234:global::System.Windows.Forms.HighDpiMode|}.{{mode}});
                }
            }
            """));
    }
}
