<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetCurrent)</TargetFramework>
    <AssemblyName>LibreWinForms.Platform</AssemblyName>
    <RootNamespace>LibreWinForms.Platform</RootNamespace>
    <Nullable>enable</Nullable>
    <Deterministic>true</Deterministic>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <StrongNameKeyId>ECMA</StrongNameKeyId>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <None Remove="tests\**\*" />
  </ItemGroup>

</Project>
