// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Drawing;
using System.Windows.Forms;
using FluentAssertions;
using Xunit;

namespace LibreWinForms.CanonicalLifecycle.Tests;

public partial class CanonicalLifecycleTests
{
    // Captured from original Microsoft WinForms 11 preview5 on Windows ARM64
    // 10.0.26200.9457, not generated by the portable renderer. Every pixel of the
    // 8x8 target is retained; symbols map the reference system color identities.
    public static IEnumerable<object[]> NativeFrameEdgePixels()
    {
        yield return [Border3DStyle.RaisedOuter, new[] { "MMMMMMMM", "MMMMMMMM", "MMLLLKMM", "MMLCCKMM", "MMLCCKMM", "MMKKKKMM", "MMMMMMMM", "MMMMMMMM" }];
        yield return [Border3DStyle.SunkenOuter, new[] { "MMMMMMMM", "MMMMMMMM", "MMDDDWMM", "MMDCCWMM", "MMDCCWMM", "MMWWWWMM", "MMMMMMMM", "MMMMMMMM" }];
        yield return [Border3DStyle.RaisedInner, new[] { "MMMMMMMM", "MMMMMMMM", "MMWWWDMM", "MMWCCDMM", "MMWCCDMM", "MMDDDDMM", "MMMMMMMM", "MMMMMMMM" }];
        yield return [Border3DStyle.Raised, new[] { "MMMMMMMM", "MMMMMMMM", "MMLLLKMM", "MMLWDKMM", "MMLDDKMM", "MMKKKKMM", "MMMMMMMM", "MMMMMMMM" }];
        yield return [Border3DStyle.Etched, new[] { "MMMMMMMM", "MMMMMMMM", "MMDDDWMM", "MMDWDWMM", "MMDDDWMM", "MMWWWWMM", "MMMMMMMM", "MMMMMMMM" }];
        yield return [Border3DStyle.SunkenInner, new[] { "MMMMMMMM", "MMMMMMMM", "MMKKKLMM", "MMKCCLMM", "MMKCCLMM", "MMLLLLMM", "MMMMMMMM", "MMMMMMMM" }];
        yield return [Border3DStyle.Bump, new[] { "MMMMMMMM", "MMMMMMMM", "MMLLLKMM", "MMLKLKMM", "MMLLLKMM", "MMKKKKMM", "MMMMMMMM", "MMMMMMMM" }];
        yield return [Border3DStyle.Sunken, new[] { "MMMMMMMM", "MMMMMMMM", "MMDDDWMM", "MMDKLWMM", "MMDLLWMM", "MMWWWWMM", "MMMMMMMM", "MMMMMMMM" }];
        yield return [Border3DStyle.Adjust, new[] { "CCCCCCCC", "CCCCCCCC", "CCCCCCCC", "CCCCCCCC", "CCCCCCCC", "CCCCCCCC", "CCCCCCCC", "CCCCCCCC" }];
        yield return [Border3DStyle.Flat, new[] { "MMMMMMMM", "MMMMMMMM", "MMDDDDMM", "MMDCCDMM", "MMDCCDMM", "MMDDDDMM", "MMMMMMMM", "MMMMMMMM" }];
    }

    [Theory]
    [MemberData(nameof(NativeFrameEdgePixels))]
    public void PortableTextBoxFrame_DrawEdgeMatchesMicrosoftPixels(Border3DStyle style, string[] rows)
    {
        UseHeadlessPlatform(autoCloseWindows: false);
        using Bitmap bitmap = new(8, 8);
        using (Graphics graphics = Graphics.FromImage(bitmap))
        {
            graphics.Clear(Color.Magenta);
            ControlPaint.DrawBorder3D(graphics, new Rectangle(2, 2, 4, 4), style, Border3DSide.All);
        }

        for (int y = 0; y < 8; y++)
        for (int x = 0; x < 8; x++)
        {
            Color expected = rows[y][x] switch
            {
                'M' => Color.Magenta, 'D' => SystemColors.ControlDark,
                'K' => SystemColors.ControlDarkDark, 'L' => SystemColors.ControlLight,
                'W' => SystemColors.ControlLightLight, 'C' => SystemColors.Control,
                _ => throw new InvalidOperationException("Unknown native reference color.")
            };
            bitmap.GetPixel(x, y).ToArgb().Should().Be(expected.ToArgb(), $"native {style} pixel ({x},{y})");
        }
    }

    [Theory]
    [InlineData(96)]
    [InlineData(120)]
    [InlineData(144)]
    [InlineData(192)]
    [InlineData(240)]
    [InlineData(288)]
    public void PortableTextBoxFrame_BorderMetricsRetainNativeDpiPolicy(int dpi)
    {
        var platform = UseHeadlessPlatform(autoCloseWindows: false);
        SystemInformation.GetBorderSizeForDpi(dpi).Should().Be(new Size(11, 13));
        platform.BorderSizeValue = new(1, 1);
        SystemInformation.GetBorderSizeForDpi(dpi).Should().Be(new Size(1, 1));
    }

    [Theory]
    [InlineData(BorderStyle.None, 120, 40, 120, 40, 70, 18)]
    [InlineData(BorderStyle.FixedSingle, 118, 38, 120, 40, 72, 20)]
    [InlineData(BorderStyle.Fixed3D, 116, 36, 116, 36, 74, 22)]
    public void PortableTextBoxFrame_ClientLifecycleMatchesMicrosoftEdit(
        BorderStyle border, int beforeWidth, int beforeHeight, int afterWidth, int afterHeight,
        int requestedWidth, int requestedHeight)
    {
        UseHeadlessPlatform(autoCloseWindows: false).BorderSizeValue = new(1, 1);
        using TextBox editor = new() { AutoSize = false, BorderStyle = border, Size = new Size(120, 40) };
        editor.ClientSize.Should().Be(new Size(beforeWidth, beforeHeight));
        _ = editor.Handle;
        editor.ClientSize.Should().Be(new Size(afterWidth, afterHeight));
        editor.ClientSize = new Size(70, 18);
        editor.Size.Should().Be(new Size(requestedWidth, requestedHeight));
        editor.ClientSize.Should().Be(new Size(70, 18));
        using Graphics graphics = editor.CreateGraphics();
        int inset = border == BorderStyle.Fixed3D ? 4 : 0;
        graphics.VisibleClipBounds.Should().Be(new RectangleF(0, 0, requestedWidth - inset, requestedHeight - inset));
    }

    [Fact]
    public void PortableTextBoxFrame_NonClientBorderDoesNotClickThroughToParent()
    {
        var platform = UseHeadlessPlatform(autoCloseWindows: false);
        using Form form = new() { AutoScaleMode = AutoScaleMode.None, ClientSize = new Size(200, 100) };
        using TextBox editor = new() { AutoSize = false, Bounds = new Rectangle(10, 20, 80, 30) };
        form.Controls.Add(editor);
        int parentClicks = 0, editorClicks = 0;
        form.MouseDown += (_, _) => parentClicks++;
        editor.MouseDown += (_, _) => editorClicks++;
        form.Show();
        platform.SendInput(LibreWinForms.Platform.LibreInputEventKind.PointerDown,
            position: new(10, 35), button: LibreWinForms.Platform.LibrePointerButton.Primary);
        platform.SendInput(LibreWinForms.Platform.LibreInputEventKind.PointerUp,
            position: new(10, 35), button: LibreWinForms.Platform.LibrePointerButton.Primary);
        parentClicks.Should().Be(0);
        editorClicks.Should().Be(0);
        platform.SendInput(LibreWinForms.Platform.LibreInputEventKind.PointerDown,
            position: new(14, 24), button: LibreWinForms.Platform.LibrePointerButton.Primary);
        editorClicks.Should().Be(1);
        parentClicks.Should().Be(0);
        form.Close();
    }

    [Fact]
    public void PortableTextBoxFrame_FormattedSourceGeometryKeepsNativeClientOffsets()
    {
        if (RunDpiCaseInNewProcess(retainedTextLayout: true)) return;
        RunRetainedEditor((platform, _, editor, _) =>
        {
            platform.BorderSizeValue = new(1, 1);
            foreach (BorderStyle border in Enum.GetValues<BorderStyle>())
            foreach (bool multiline in new[] { false, true })
            {
                editor.BorderStyle = border;
                editor.Multiline = multiline;
                editor.Text = "Alice";
                editor.Size = new Size(120, 40);
                editor.Select(0, 0);
                editor.Record();
                int margin = border switch { BorderStyle.FixedSingle => 2, BorderStyle.Fixed3D => 1, _ => 0 };
                editor.GetPositionFromCharIndex(0).Should().Be(new Point(margin, multiline ? margin : 0));
                editor.GetCharIndexFromPosition(new Point(margin, margin)).Should().Be(0);
            }
        });
    }
}
