<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetCurrent)</TargetFramework>
    <AssemblyName>LibreWinForms.ProGPU.Tests</AssemblyName>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\eng\PopupInteractionApp\PopupInteractionStartup.cs" Link="SourceContracts\PopupInteractionStartup.cs" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.DotNet.XUnitV3Extensions" />
    <ProjectReference Include="..\LibreWinForms.ProGPU.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\SilkWindowService.cs" Link="SourceContracts\SilkWindowService.cs"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\LibreWinForms.Sdk\targets\LibreWinForms.Sdk.targets" Link="SourceContracts\LibreWinForms.Sdk.targets"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
